server:
    port: 8081
    servlet:
         context-path: /myapp
         
spring:
    jpa:
      hibernate:
          ddl-auto: update
    datasource:
            url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/db_example
            username: root
            password: root         
